steps:
  - type: filter
    parameters:
      inputs: 
        - WikiMatrix.en-ru.en
        - WikiMatrix.en-ru.ru
      outputs: 
        - WikiMatrix_filtered.en-ru.en
        - WikiMatrix_filtered.en-ru.ru
      filters: 
        - TenWordsLengthFilter:
            unit: word            
            max_length: 10
          module: len_filter
