common:
  output_directory: .
steps:
- type: filter
  parameters:
    inputs:
    - WikiMatrix.en-ru.en
    - WikiMatrix.en-ru.ru
    outputs:
    - text_f.en-ru.en
    - text_f.en-ru.ru
    filters:
    - TenWordsLengthFilter:
        max_length: 10
      module: len_filter
